server:
  port: 9921 #提供者的端口
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
#  config: classpath:logback-spring.xml

nacos:
  config:
    server-addr: 127.0.0.1:8848
    group: NAOCS-SPRING-CLOUD-GATEWAY
    file-extension: json
    data-id: spring-cloud-gateway.json
