DROP TABLE IF EXISTS user;
CREATE TABLE user
(
  id BIGINT(20) NOT NULL COMMENT '主键',
  provider_id BIGINT(20) NOT NULL COMMENT '服务商ID',
  name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
  PRIMARY KEY (id)
);
