server:
  port: 9022 #提供者的端口
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug

spring:
  application:
    name: spring-cloud-gateway-service
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 5
    host: 127.0.0.1
    port: 6379
    password: 123   # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
gateway:
  log:
    enable: false
